### PR TITLE
Make it usable with any language

### PR DESCRIPTION
**Pull request by taai**
This closes the #16 issue "Other languages".
Now you should be able to use any language (locale) defined in config file.

### CODE REVIEW

**Comment by Anahkiasen** [comment]
The last method shouldn't be necessary, I think Polyglot's Lang class has a method for that no ?

**Comment by taai** [comment]
@Anahkiasen Do you mean `Polyglot\Lang::getAvailable` method? I don't see how it is used by `Polyglot\Polyglot` class. And the Laravel's `Config::get` is being used in `Polyglot\Polyglot::getLangClass` method anyway...

Another reason why I did create `Polyglot\Polyglot::getLocales` method is flexibility. For example, if you need to get your supported locales from another place, for example in `config/app.php`, you just override the `Polyglot\Polyglot::getLocales` method. In your project you can also hard-code the locales for your models, if you would like it better:

``` php
protected function getLocales()
{
    return array('en', 'fr', 'lv');
}
```

First I thought about storing the locales in `protected $locales = array();` attribute, but this is more flexible.

**Comment by Anahkiasen** [comment]
The Polyglot\Lang class is swapped at runtime for the Lang class so you could call `Lang::getAvailable` like you're calling `Config::get` but that way if the config option change I don't have to change it in two places. But I mean it's the same thing.

But keep the additional method in the Polyglot model for easy override like you mentioned. Simply, you don't have to call the config class directly.

**Comment by taai** [comment]
@Anahkiasen How to access it? Through App instance?

**Comment by Anahkiasen** [comment]
No no, I mean it actually extends and swaps the `Lang` class so you can do `use Lang` and then `Lang::something`.

**Comment by taai** [comment]
@Anahkiasen It seems that it is not possible to do so, because `getAvailable` method is not static. So, I can't do `Lang::getAvailable()`. At least not like you wrote. Only way I found to access the `Polyglot\Lang` class instance was by using Laravel's `app()` helper.

``` php
app('translator')->getAvailable()
```

Ayway, the result is the same as by using `Config::get('polyglot::locales')`.

I haven't dag into Laravel so deep yet and I don't know what is the "right" way to get the config, but at least this works.

What to do now? Do you have a working solution to access `Polyglot\Lang::getAvailable` and get the config out of it? Or use one of solutions I have shown? And is this so important anyway? :)

**Comment by Anahkiasen** [comment]
Yeah no forget about it I forgot we were in the model. But I mean it'd work in an actual application, even if it's not static, because Polyglot\Lang is swapped under the Lang facade. It just doesn't work in the tests. But yeah leave it like that.

**Pull request merged**
